export 'criar_pedidos.dart' show criarPedidos;
export 'add_cart_evitar_duplicar_sem_variente.dart'
    show addCartEvitarDuplicarSemVariente;
export 'promo_relampagolimpeza.dart' show promoRelampagolimpeza;
export 'aplicar_desconto_frete19.dart' show aplicarDescontoFrete19;
export 'aplicar_desconto_frete50.dart' show aplicarDescontoFrete50;
export 'update_selecionado_to_true2.dart' show updateSelecionadoToTrue2;
export 'salvar_afiliado_no_app_state.dart' show salvarAfiliadoNoAppState;
export 'checkout_final_sem_frete.dart' show checkoutFinalSemFrete;
export 'create_coupon_for_users.dart' show createCouponForUsers;
export 'crear_cupom_novo_user.dart' show crearCupomNovoUser;
export 'cupom_mais10.dart' show cupomMais10;
export 'cupom_mais19.dart' show cupomMais19;
export 'update_selecionado_to_true.dart' show updateSelecionadoToTrue;
export 'update_selecionar_todos_based_on_selecionado.dart'
    show updateSelecionarTodosBasedOnSelecionado;
export 'calcular_frete2.dart' show calcularFrete2;
export 'frete_cupom_novo.dart' show freteCupomNovo;
export 'gerar_rastreio.dart' show gerarRastreio;
export 'pedido_pago_update.dart' show pedidoPagoUpdate;
export 'soma_frete_cartao.dart' show somaFreteCartao;
export 'atualizar_time24h.dart' show atualizarTime24h;
export 'freteantess.dart' show freteantess;
export 'i_c_m_scriar.dart' show iCMScriar;
export 'formatar_sugestoes_palavras_chave.dart'
    show formatarSugestoesPalavrasChave;
export 'posicao_foto.dart' show posicaoFoto;
export 'checkout_final.dart' show checkoutFinal;
export 'aplicar_desconto_frete.dart' show aplicarDescontoFrete;
export 'remover_frete_promo.dart' show removerFretePromo;
export 'calcular_frete_carrinho_final.dart' show calcularFreteCarrinhoFinal;
export 'criar_promo_relampago.dart' show criarPromoRelampago;
export 'promo_relampago_update.dart' show promoRelampagoUpdate;
export 'generate_product_deep_link.dart' show generateProductDeepLink;
export 'init_branch.dart' show initBranch;
export 'handle_branch_deeplink.dart' show handleBranchDeeplink;
export 'criar_carrinho_pos_login.dart' show criarCarrinhoPosLogin;
export 'add_cart_evitar_duplicar.dart' show addCartEvitarDuplicar;
export 'fazer_pagamento.dart' show fazerPagamento;
export 'download_file.dart' show downloadFile;
export 'videosave_action.dart' show videosaveAction;
export 'testecodigo.dart' show testecodigo;
export 'notificar_venda.dart' show notificarVenda;
export 'play_notification_sound.dart' show playNotificationSound;
export 'teste_login_google_melhorado.dart' show testeLoginGoogleMelhorado;
export 'download_video.dart' show downloadVideo;
export 'check_firebase_config.dart' show checkFirebaseConfig;
export 'detectar_android_ou_i_o_s.dart' show detectarAndroidOuIOS;
export 'firebase_diagnostic.dart' show firebaseDiagnostic;
